service: sls-form-mail

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  profile: serverless
#  stage: dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"

functions:
  StripeWebhook:
    handler: handler
    events:
      - http:
          path: send
          method: post